<?xml version="1.0" encoding="utf-8"?><Database Name="SeasonalFoods" Class="SeasonalFoodsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-CQ1BQQH5\SQLEXPRESS;Initial Catalog=SeasonalFoods;User ID=sa" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="SeasonalFoodsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TAI_KHOAN" Member="TAI_KHOANs">
    <Type Name="TAI_KHOAN">
      <Column Name="TENDN" Type="System.String" DbType="Char(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="MATKHAU" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="TAI_KHOAN_NGUOIDUNG_NHOM_ND" Member="NGUOIDUNG_NHOM_NDs" ThisKey="TENDN" OtherKey="TenDangNhap" Type="NGUOIDUNG_NHOM_ND" />
      <Association Name="NHANVIEN_TAI_KHOAN" Member="NHANVIEN" ThisKey="MANV" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CHUCVU" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PHAI_NV" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="DIACHI_NV" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="SDT_NV" Type="System.Decimal" DbType="Decimal(10,0)" CanBeNull="true" />
      <Association Name="NHANVIEN_TAI_KHOAN" Member="TAI_KHOANs" ThisKey="MANV" OtherKey="MANV" Type="TAI_KHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.MAN_HINH" Member="MAN_HINHs">
    <Type Name="MAN_HINH">
      <Column Name="MaManHinh" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenManHinh" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="MAN_HINH_PHAN_QUYEN" Member="PHAN_QUYENs" ThisKey="MaManHinh" OtherKey="MaManHinh" Type="PHAN_QUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG_NHOM_ND" Member="NGUOIDUNG_NHOM_NDs">
    <Type Name="NGUOIDUNG_NHOM_ND">
      <Column Name="TenDangNhap" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNhomNguoiDung" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="TAI_KHOAN_NGUOIDUNG_NHOM_ND" Member="TAI_KHOAN" ThisKey="TenDangNhap" OtherKey="TENDN" Type="TAI_KHOAN" IsForeignKey="true" />
      <Association Name="NHOM_NGUOI_DUNG_NGUOIDUNG_NHOM_ND" Member="NHOM_NGUOI_DUNG" ThisKey="MaNhomNguoiDung" OtherKey="MaNhom" Type="NHOM_NGUOI_DUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHOM_NGUOI_DUNG" Member="NHOM_NGUOI_DUNGs">
    <Type Name="NHOM_NGUOI_DUNG">
      <Column Name="MaNhom" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="NHOM_NGUOI_DUNG_NGUOIDUNG_NHOM_ND" Member="NGUOIDUNG_NHOM_NDs" ThisKey="MaNhom" OtherKey="MaNhomNguoiDung" Type="NGUOIDUNG_NHOM_ND" />
      <Association Name="NHOM_NGUOI_DUNG_PHAN_QUYEN" Member="PHAN_QUYENs" ThisKey="MaNhom" OtherKey="MaNhomNguoiDung" Type="PHAN_QUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.PHAN_QUYEN" Member="PHAN_QUYENs">
    <Type Name="PHAN_QUYEN">
      <Column Name="MaNhomNguoiDung" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaManHinh" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CoQuyen" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MAN_HINH_PHAN_QUYEN" Member="MAN_HINH" ThisKey="MaManHinh" OtherKey="MaManHinh" Type="MAN_HINH" IsForeignKey="true" />
      <Association Name="NHOM_NGUOI_DUNG_PHAN_QUYEN" Member="NHOM_NGUOI_DUNG" ThisKey="MaNhomNguoiDung" OtherKey="MaNhom" Type="NHOM_NGUOI_DUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANH_MUC_SP" Member="DANH_MUC_SPs">
    <Type Name="DANH_MUC_SP">
      <Column Name="MALOAI" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="DANH_MUC_SP_HANGHOA" Member="HANGHOAs" ThisKey="MALOAI" OtherKey="MALOAI" Type="HANGHOA" />
    </Type>
  </Table>
  <Table Name="dbo.HANGHOA" Member="HANGHOAs">
    <Type Name="HANGHOA">
      <Column Name="MASP" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MALOAI" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DANH_MUC_SP_HANGHOA" Member="DANH_MUC_SP" ThisKey="MALOAI" OtherKey="MALOAI" Type="DANH_MUC_SP" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.getHangHoa_Loai" Method="getHangHoa_Loai" IsComposable="true">
    <Parameter Name="maLoai" Type="System.String" DbType="Char(10)" />
    <ElementType Name="getHangHoa_LoaiResult">
      <Column Name="MASP" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIA_BAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DVT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>