#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SeasonalFoods")]
	public partial class SeasonalFoodsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTAI_KHOAN(TAI_KHOAN instance);
    partial void UpdateTAI_KHOAN(TAI_KHOAN instance);
    partial void DeleteTAI_KHOAN(TAI_KHOAN instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertMAN_HINH(MAN_HINH instance);
    partial void UpdateMAN_HINH(MAN_HINH instance);
    partial void DeleteMAN_HINH(MAN_HINH instance);
    partial void InsertNGUOIDUNG_NHOM_ND(NGUOIDUNG_NHOM_ND instance);
    partial void UpdateNGUOIDUNG_NHOM_ND(NGUOIDUNG_NHOM_ND instance);
    partial void DeleteNGUOIDUNG_NHOM_ND(NGUOIDUNG_NHOM_ND instance);
    partial void InsertNHOM_NGUOI_DUNG(NHOM_NGUOI_DUNG instance);
    partial void UpdateNHOM_NGUOI_DUNG(NHOM_NGUOI_DUNG instance);
    partial void DeleteNHOM_NGUOI_DUNG(NHOM_NGUOI_DUNG instance);
    partial void InsertPHAN_QUYEN(PHAN_QUYEN instance);
    partial void UpdatePHAN_QUYEN(PHAN_QUYEN instance);
    partial void DeletePHAN_QUYEN(PHAN_QUYEN instance);
    partial void InsertDANH_MUC_SP(DANH_MUC_SP instance);
    partial void UpdateDANH_MUC_SP(DANH_MUC_SP instance);
    partial void DeleteDANH_MUC_SP(DANH_MUC_SP instance);
    partial void InsertHANGHOA(HANGHOA instance);
    partial void UpdateHANGHOA(HANGHOA instance);
    partial void DeleteHANGHOA(HANGHOA instance);
    #endregion
		
		public SeasonalFoodsDataContext() : 
				base(global::DAL.Properties.Settings.Default.SeasonalFoodsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SeasonalFoodsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeasonalFoodsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeasonalFoodsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SeasonalFoodsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TAI_KHOAN> TAI_KHOANs
		{
			get
			{
				return this.GetTable<TAI_KHOAN>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<MAN_HINH> MAN_HINHs
		{
			get
			{
				return this.GetTable<MAN_HINH>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG_NHOM_ND> NGUOIDUNG_NHOM_NDs
		{
			get
			{
				return this.GetTable<NGUOIDUNG_NHOM_ND>();
			}
		}
		
		public System.Data.Linq.Table<NHOM_NGUOI_DUNG> NHOM_NGUOI_DUNGs
		{
			get
			{
				return this.GetTable<NHOM_NGUOI_DUNG>();
			}
		}
		
		public System.Data.Linq.Table<PHAN_QUYEN> PHAN_QUYENs
		{
			get
			{
				return this.GetTable<PHAN_QUYEN>();
			}
		}
		
		public System.Data.Linq.Table<DANH_MUC_SP> DANH_MUC_SPs
		{
			get
			{
				return this.GetTable<DANH_MUC_SP>();
			}
		}
		
		public System.Data.Linq.Table<HANGHOA> HANGHOAs
		{
			get
			{
				return this.GetTable<HANGHOA>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.getHangHoa_Loai", IsComposable=true)]
		public IQueryable<getHangHoa_LoaiResult> getHangHoa_Loai([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Char(10)")] string maLoai)
		{
			return this.CreateMethodCallQuery<getHangHoa_LoaiResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maLoai);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAI_KHOAN")]
	public partial class TAI_KHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TENDN;
		
		private string _MANV;
		
		private string _MATKHAU;
		
		private string _HOATDONG;
		
		private EntitySet<NGUOIDUNG_NHOM_ND> _NGUOIDUNG_NHOM_NDs;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnHOATDONGChanging(string value);
    partial void OnHOATDONGChanged();
    #endregion
		
		public TAI_KHOAN()
		{
			this._NGUOIDUNG_NHOM_NDs = new EntitySet<NGUOIDUNG_NHOM_ND>(new Action<NGUOIDUNG_NHOM_ND>(this.attach_NGUOIDUNG_NHOM_NDs), new Action<NGUOIDUNG_NHOM_ND>(this.detach_NGUOIDUNG_NHOM_NDs));
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="Char(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="Char(20)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOATDONG", DbType="VarChar(5)")]
		public string HOATDONG
		{
			get
			{
				return this._HOATDONG;
			}
			set
			{
				if ((this._HOATDONG != value))
				{
					this.OnHOATDONGChanging(value);
					this.SendPropertyChanging();
					this._HOATDONG = value;
					this.SendPropertyChanged("HOATDONG");
					this.OnHOATDONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_NGUOIDUNG_NHOM_ND", Storage="_NGUOIDUNG_NHOM_NDs", ThisKey="TENDN", OtherKey="TenDangNhap")]
		public EntitySet<NGUOIDUNG_NHOM_ND> NGUOIDUNG_NHOM_NDs
		{
			get
			{
				return this._NGUOIDUNG_NHOM_NDs;
			}
			set
			{
				this._NGUOIDUNG_NHOM_NDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAI_KHOAN", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.TAI_KHOANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TAI_KHOANs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NGUOIDUNG_NHOM_NDs(NGUOIDUNG_NHOM_ND entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = this;
		}
		
		private void detach_NGUOIDUNG_NHOM_NDs(NGUOIDUNG_NHOM_ND entity)
		{
			this.SendPropertyChanging();
			entity.TAI_KHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _TENNV;
		
		private string _CHUCVU;
		
		private string _PHAI_NV;
		
		private string _DIACHI_NV;
		
		private string _EMAIL;
		
		private System.Nullable<decimal> _SDT_NV;
		
		private EntitySet<TAI_KHOAN> _TAI_KHOANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnTENNVChanging(string value);
    partial void OnTENNVChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    partial void OnPHAI_NVChanging(string value);
    partial void OnPHAI_NVChanged();
    partial void OnDIACHI_NVChanging(string value);
    partial void OnDIACHI_NVChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnSDT_NVChanging(System.Nullable<decimal> value);
    partial void OnSDT_NVChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._TAI_KHOANs = new EntitySet<TAI_KHOAN>(new Action<TAI_KHOAN>(this.attach_TAI_KHOANs), new Action<TAI_KHOAN>(this.detach_TAI_KHOANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNV", DbType="VarChar(50)")]
		public string TENNV
		{
			get
			{
				return this._TENNV;
			}
			set
			{
				if ((this._TENNV != value))
				{
					this.OnTENNVChanging(value);
					this.SendPropertyChanging();
					this._TENNV = value;
					this.SendPropertyChanged("TENNV");
					this.OnTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="VarChar(50)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHAI_NV", DbType="VarChar(3)")]
		public string PHAI_NV
		{
			get
			{
				return this._PHAI_NV;
			}
			set
			{
				if ((this._PHAI_NV != value))
				{
					this.OnPHAI_NVChanging(value);
					this.SendPropertyChanging();
					this._PHAI_NV = value;
					this.SendPropertyChanged("PHAI_NV");
					this.OnPHAI_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI_NV", DbType="VarChar(100)")]
		public string DIACHI_NV
		{
			get
			{
				return this._DIACHI_NV;
			}
			set
			{
				if ((this._DIACHI_NV != value))
				{
					this.OnDIACHI_NVChanging(value);
					this.SendPropertyChanging();
					this._DIACHI_NV = value;
					this.SendPropertyChanged("DIACHI_NV");
					this.OnDIACHI_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NChar(20)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT_NV", DbType="Decimal(10,0)")]
		public System.Nullable<decimal> SDT_NV
		{
			get
			{
				return this._SDT_NV;
			}
			set
			{
				if ((this._SDT_NV != value))
				{
					this.OnSDT_NVChanging(value);
					this.SendPropertyChanging();
					this._SDT_NV = value;
					this.SendPropertyChanged("SDT_NV");
					this.OnSDT_NVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAI_KHOAN", Storage="_TAI_KHOANs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<TAI_KHOAN> TAI_KHOANs
		{
			get
			{
				return this._TAI_KHOANs;
			}
			set
			{
				this._TAI_KHOANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TAI_KHOANs(TAI_KHOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_TAI_KHOANs(TAI_KHOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAN_HINH")]
	public partial class MAN_HINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaManHinh;
		
		private string _TenManHinh;
		
		private EntitySet<PHAN_QUYEN> _PHAN_QUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaManHinhChanging(string value);
    partial void OnMaManHinhChanged();
    partial void OnTenManHinhChanging(string value);
    partial void OnTenManHinhChanged();
    #endregion
		
		public MAN_HINH()
		{
			this._PHAN_QUYENs = new EntitySet<PHAN_QUYEN>(new Action<PHAN_QUYEN>(this.attach_PHAN_QUYENs), new Action<PHAN_QUYEN>(this.detach_PHAN_QUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenManHinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenManHinh
		{
			get
			{
				return this._TenManHinh;
			}
			set
			{
				if ((this._TenManHinh != value))
				{
					this.OnTenManHinhChanging(value);
					this.SendPropertyChanging();
					this._TenManHinh = value;
					this.SendPropertyChanged("TenManHinh");
					this.OnTenManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAN_HINH_PHAN_QUYEN", Storage="_PHAN_QUYENs", ThisKey="MaManHinh", OtherKey="MaManHinh")]
		public EntitySet<PHAN_QUYEN> PHAN_QUYENs
		{
			get
			{
				return this._PHAN_QUYENs;
			}
			set
			{
				this._PHAN_QUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHAN_QUYENs(PHAN_QUYEN entity)
		{
			this.SendPropertyChanging();
			entity.MAN_HINH = this;
		}
		
		private void detach_PHAN_QUYENs(PHAN_QUYEN entity)
		{
			this.SendPropertyChanging();
			entity.MAN_HINH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG_NHOM_ND")]
	public partial class NGUOIDUNG_NHOM_ND : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MaNhomNguoiDung;
		
		private string _GhiChu;
		
		private EntityRef<TAI_KHOAN> _TAI_KHOAN;
		
		private EntityRef<NHOM_NGUOI_DUNG> _NHOM_NGUOI_DUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMaNhomNguoiDungChanging(string value);
    partial void OnMaNhomNguoiDungChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public NGUOIDUNG_NHOM_ND()
		{
			this._TAI_KHOAN = default(EntityRef<TAI_KHOAN>);
			this._NHOM_NGUOI_DUNG = default(EntityRef<NHOM_NGUOI_DUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					if (this._TAI_KHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNguoiDung", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomNguoiDung
		{
			get
			{
				return this._MaNhomNguoiDung;
			}
			set
			{
				if ((this._MaNhomNguoiDung != value))
				{
					if (this._NHOM_NGUOI_DUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNhomNguoiDung = value;
					this.SendPropertyChanged("MaNhomNguoiDung");
					this.OnMaNhomNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAI_KHOAN_NGUOIDUNG_NHOM_ND", Storage="_TAI_KHOAN", ThisKey="TenDangNhap", OtherKey="TENDN", IsForeignKey=true)]
		public TAI_KHOAN TAI_KHOAN
		{
			get
			{
				return this._TAI_KHOAN.Entity;
			}
			set
			{
				TAI_KHOAN previousValue = this._TAI_KHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAI_KHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAI_KHOAN.Entity = null;
						previousValue.NGUOIDUNG_NHOM_NDs.Remove(this);
					}
					this._TAI_KHOAN.Entity = value;
					if ((value != null))
					{
						value.NGUOIDUNG_NHOM_NDs.Add(this);
						this._TenDangNhap = value.TENDN;
					}
					else
					{
						this._TenDangNhap = default(string);
					}
					this.SendPropertyChanged("TAI_KHOAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOM_NGUOI_DUNG_NGUOIDUNG_NHOM_ND", Storage="_NHOM_NGUOI_DUNG", ThisKey="MaNhomNguoiDung", OtherKey="MaNhom", IsForeignKey=true)]
		public NHOM_NGUOI_DUNG NHOM_NGUOI_DUNG
		{
			get
			{
				return this._NHOM_NGUOI_DUNG.Entity;
			}
			set
			{
				NHOM_NGUOI_DUNG previousValue = this._NHOM_NGUOI_DUNG.Entity;
				if (((previousValue != value) 
							|| (this._NHOM_NGUOI_DUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHOM_NGUOI_DUNG.Entity = null;
						previousValue.NGUOIDUNG_NHOM_NDs.Remove(this);
					}
					this._NHOM_NGUOI_DUNG.Entity = value;
					if ((value != null))
					{
						value.NGUOIDUNG_NHOM_NDs.Add(this);
						this._MaNhomNguoiDung = value.MaNhom;
					}
					else
					{
						this._MaNhomNguoiDung = default(string);
					}
					this.SendPropertyChanged("NHOM_NGUOI_DUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHOM_NGUOI_DUNG")]
	public partial class NHOM_NGUOI_DUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _TenNhom;
		
		private string _GhiChu;
		
		private EntitySet<NGUOIDUNG_NHOM_ND> _NGUOIDUNG_NHOM_NDs;
		
		private EntitySet<PHAN_QUYEN> _PHAN_QUYENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public NHOM_NGUOI_DUNG()
		{
			this._NGUOIDUNG_NHOM_NDs = new EntitySet<NGUOIDUNG_NHOM_ND>(new Action<NGUOIDUNG_NHOM_ND>(this.attach_NGUOIDUNG_NHOM_NDs), new Action<NGUOIDUNG_NHOM_ND>(this.detach_NGUOIDUNG_NHOM_NDs));
			this._PHAN_QUYENs = new EntitySet<PHAN_QUYEN>(new Action<PHAN_QUYEN>(this.attach_PHAN_QUYENs), new Action<PHAN_QUYEN>(this.detach_PHAN_QUYENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(200)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOM_NGUOI_DUNG_NGUOIDUNG_NHOM_ND", Storage="_NGUOIDUNG_NHOM_NDs", ThisKey="MaNhom", OtherKey="MaNhomNguoiDung")]
		public EntitySet<NGUOIDUNG_NHOM_ND> NGUOIDUNG_NHOM_NDs
		{
			get
			{
				return this._NGUOIDUNG_NHOM_NDs;
			}
			set
			{
				this._NGUOIDUNG_NHOM_NDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOM_NGUOI_DUNG_PHAN_QUYEN", Storage="_PHAN_QUYENs", ThisKey="MaNhom", OtherKey="MaNhomNguoiDung")]
		public EntitySet<PHAN_QUYEN> PHAN_QUYENs
		{
			get
			{
				return this._PHAN_QUYENs;
			}
			set
			{
				this._PHAN_QUYENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NGUOIDUNG_NHOM_NDs(NGUOIDUNG_NHOM_ND entity)
		{
			this.SendPropertyChanging();
			entity.NHOM_NGUOI_DUNG = this;
		}
		
		private void detach_NGUOIDUNG_NHOM_NDs(NGUOIDUNG_NHOM_ND entity)
		{
			this.SendPropertyChanging();
			entity.NHOM_NGUOI_DUNG = null;
		}
		
		private void attach_PHAN_QUYENs(PHAN_QUYEN entity)
		{
			this.SendPropertyChanging();
			entity.NHOM_NGUOI_DUNG = this;
		}
		
		private void detach_PHAN_QUYENs(PHAN_QUYEN entity)
		{
			this.SendPropertyChanging();
			entity.NHOM_NGUOI_DUNG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHAN_QUYEN")]
	public partial class PHAN_QUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhomNguoiDung;
		
		private string _MaManHinh;
		
		private bool _CoQuyen;
		
		private EntityRef<MAN_HINH> _MAN_HINH;
		
		private EntityRef<NHOM_NGUOI_DUNG> _NHOM_NGUOI_DUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomNguoiDungChanging(string value);
    partial void OnMaNhomNguoiDungChanged();
    partial void OnMaManHinhChanging(string value);
    partial void OnMaManHinhChanged();
    partial void OnCoQuyenChanging(bool value);
    partial void OnCoQuyenChanged();
    #endregion
		
		public PHAN_QUYEN()
		{
			this._MAN_HINH = default(EntityRef<MAN_HINH>);
			this._NHOM_NGUOI_DUNG = default(EntityRef<NHOM_NGUOI_DUNG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomNguoiDung", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomNguoiDung
		{
			get
			{
				return this._MaNhomNguoiDung;
			}
			set
			{
				if ((this._MaNhomNguoiDung != value))
				{
					if (this._NHOM_NGUOI_DUNG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._MaNhomNguoiDung = value;
					this.SendPropertyChanged("MaNhomNguoiDung");
					this.OnMaNhomNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					if (this._MAN_HINH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoQuyen", DbType="Bit NOT NULL")]
		public bool CoQuyen
		{
			get
			{
				return this._CoQuyen;
			}
			set
			{
				if ((this._CoQuyen != value))
				{
					this.OnCoQuyenChanging(value);
					this.SendPropertyChanging();
					this._CoQuyen = value;
					this.SendPropertyChanged("CoQuyen");
					this.OnCoQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAN_HINH_PHAN_QUYEN", Storage="_MAN_HINH", ThisKey="MaManHinh", OtherKey="MaManHinh", IsForeignKey=true)]
		public MAN_HINH MAN_HINH
		{
			get
			{
				return this._MAN_HINH.Entity;
			}
			set
			{
				MAN_HINH previousValue = this._MAN_HINH.Entity;
				if (((previousValue != value) 
							|| (this._MAN_HINH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAN_HINH.Entity = null;
						previousValue.PHAN_QUYENs.Remove(this);
					}
					this._MAN_HINH.Entity = value;
					if ((value != null))
					{
						value.PHAN_QUYENs.Add(this);
						this._MaManHinh = value.MaManHinh;
					}
					else
					{
						this._MaManHinh = default(string);
					}
					this.SendPropertyChanged("MAN_HINH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHOM_NGUOI_DUNG_PHAN_QUYEN", Storage="_NHOM_NGUOI_DUNG", ThisKey="MaNhomNguoiDung", OtherKey="MaNhom", IsForeignKey=true)]
		public NHOM_NGUOI_DUNG NHOM_NGUOI_DUNG
		{
			get
			{
				return this._NHOM_NGUOI_DUNG.Entity;
			}
			set
			{
				NHOM_NGUOI_DUNG previousValue = this._NHOM_NGUOI_DUNG.Entity;
				if (((previousValue != value) 
							|| (this._NHOM_NGUOI_DUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHOM_NGUOI_DUNG.Entity = null;
						previousValue.PHAN_QUYENs.Remove(this);
					}
					this._NHOM_NGUOI_DUNG.Entity = value;
					if ((value != null))
					{
						value.PHAN_QUYENs.Add(this);
						this._MaNhomNguoiDung = value.MaNhom;
					}
					else
					{
						this._MaNhomNguoiDung = default(string);
					}
					this.SendPropertyChanged("NHOM_NGUOI_DUNG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DANH_MUC_SP")]
	public partial class DANH_MUC_SP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAI;
		
		private string _TENLOAI;
		
		private EntitySet<HANGHOA> _HANGHOAs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnTENLOAIChanging(string value);
    partial void OnTENLOAIChanged();
    #endregion
		
		public DANH_MUC_SP()
		{
			this._HANGHOAs = new EntitySet<HANGHOA>(new Action<HANGHOA>(this.attach_HANGHOAs), new Action<HANGHOA>(this.detach_HANGHOAs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAI", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TENLOAI
		{
			get
			{
				return this._TENLOAI;
			}
			set
			{
				if ((this._TENLOAI != value))
				{
					this.OnTENLOAIChanging(value);
					this.SendPropertyChanging();
					this._TENLOAI = value;
					this.SendPropertyChanged("TENLOAI");
					this.OnTENLOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANH_MUC_SP_HANGHOA", Storage="_HANGHOAs", ThisKey="MALOAI", OtherKey="MALOAI")]
		public EntitySet<HANGHOA> HANGHOAs
		{
			get
			{
				return this._HANGHOAs;
			}
			set
			{
				this._HANGHOAs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HANGHOAs(HANGHOA entity)
		{
			this.SendPropertyChanging();
			entity.DANH_MUC_SP = this;
		}
		
		private void detach_HANGHOAs(HANGHOA entity)
		{
			this.SendPropertyChanging();
			entity.DANH_MUC_SP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HANGHOA")]
	public partial class HANGHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MASP;
		
		private string _MALOAI;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _DVT;
		
		private string _TENSP;
		
		private EntityRef<DANH_MUC_SP> _DANH_MUC_SP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMASPChanging(string value);
    partial void OnMASPChanged();
    partial void OnMALOAIChanging(string value);
    partial void OnMALOAIChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnDVTChanging(string value);
    partial void OnDVTChanged();
    partial void OnTENSPChanging(string value);
    partial void OnTENSPChanged();
    #endregion
		
		public HANGHOA()
		{
			this._DANH_MUC_SP = default(EntityRef<DANH_MUC_SP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASP", DbType="Char(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MASP
		{
			get
			{
				return this._MASP;
			}
			set
			{
				if ((this._MASP != value))
				{
					this.OnMASPChanging(value);
					this.SendPropertyChanging();
					this._MASP = value;
					this.SendPropertyChanged("MASP");
					this.OnMASPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAI", DbType="Char(10)")]
		public string MALOAI
		{
			get
			{
				return this._MALOAI;
			}
			set
			{
				if ((this._MALOAI != value))
				{
					if (this._DANH_MUC_SP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMALOAIChanging(value);
					this.SendPropertyChanging();
					this._MALOAI = value;
					this.SendPropertyChanged("MALOAI");
					this.OnMALOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(20)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this.OnDVTChanging(value);
					this.SendPropertyChanging();
					this._DVT = value;
					this.SendPropertyChanged("DVT");
					this.OnDVTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSP", DbType="NVarChar(50)")]
		public string TENSP
		{
			get
			{
				return this._TENSP;
			}
			set
			{
				if ((this._TENSP != value))
				{
					this.OnTENSPChanging(value);
					this.SendPropertyChanging();
					this._TENSP = value;
					this.SendPropertyChanged("TENSP");
					this.OnTENSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DANH_MUC_SP_HANGHOA", Storage="_DANH_MUC_SP", ThisKey="MALOAI", OtherKey="MALOAI", IsForeignKey=true)]
		public DANH_MUC_SP DANH_MUC_SP
		{
			get
			{
				return this._DANH_MUC_SP.Entity;
			}
			set
			{
				DANH_MUC_SP previousValue = this._DANH_MUC_SP.Entity;
				if (((previousValue != value) 
							|| (this._DANH_MUC_SP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DANH_MUC_SP.Entity = null;
						previousValue.HANGHOAs.Remove(this);
					}
					this._DANH_MUC_SP.Entity = value;
					if ((value != null))
					{
						value.HANGHOAs.Add(this);
						this._MALOAI = value.MALOAI;
					}
					else
					{
						this._MALOAI = default(string);
					}
					this.SendPropertyChanged("DANH_MUC_SP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class getHangHoa_LoaiResult
	{
		
		private string _MASP;
		
		private string _TENSP;
		
		private System.Nullable<double> _GIA_BAN;
		
		private string _DVT;
		
		private System.Nullable<int> _SOLUONG;
		
		public getHangHoa_LoaiResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASP", DbType="Char(10)")]
		public string MASP
		{
			get
			{
				return this._MASP;
			}
			set
			{
				if ((this._MASP != value))
				{
					this._MASP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENSP", DbType="NVarChar(50)")]
		public string TENSP
		{
			get
			{
				return this._TENSP;
			}
			set
			{
				if ((this._TENSP != value))
				{
					this._TENSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_BAN", DbType="Float")]
		public System.Nullable<double> GIA_BAN
		{
			get
			{
				return this._GIA_BAN;
			}
			set
			{
				if ((this._GIA_BAN != value))
				{
					this._GIA_BAN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVT", DbType="NVarChar(20)")]
		public string DVT
		{
			get
			{
				return this._DVT;
			}
			set
			{
				if ((this._DVT != value))
				{
					this._DVT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this._SOLUONG = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
